### ISSUE TITLE
CNS.dll版本适配

### ISSUE THREAD

**Issue by soarqin** [mistzzt/TShock#2]
因为CNS.dll锁死了Terraria API版本号，现在只能匹配1.23的API，不能用于官方仓库最新的1.24的API
能否提供CNS.dll源代码以便自行编译支持新版的API，或者提供一些绕过API版本检测的方案?

**Comment by mistzzt** [comment]
我可以提供一个1.24的Api版本

当然你也可以通过运行TerrariaServer.exe时提供参数, 让它忽略ApiVersion加载插件

**Comment by mistzzt** [comment]
运行时候指定参数 "-ignoreversion" 不包含引号
就可以加载了.

刚刚改了一下Api版本编译了一份, 但是死活没上传上去, 只能用百度盘了...
[CNS (Api v1.24)](http://pan.baidu.com/s/1pKV41aN)

**Comment by soarqin** [comment]
谢谢

**Comment by mistzzt** [comment]
针对官方repo最近的更新, 发布了个新版本. [API v1.24](https://github.com/mistzzt/TShock/releases/tag/CNv1.2.3)
