### ISSUE TITLE
乱码了

### ISSUE THREAD

**Issue by AliceSync** [mistzzt/TShock#4]
win2008 R2 SP1 企业
![qq 20170919173150](https://user-images.githubusercontent.com/16536678/30586152-9bc84cbc-9d61-11e7-98bc-d0e65132f8fb.png)

**Comment by mistzzt** [comment]
这是原版terraria服务器问题。我有一个插件可以修复这个问题

**Comment by mistzzt** [comment]
[FixConsoleOutputForWin7.zip](https://github.com/mistzzt/TShock/files/1326009/FixConsoleOutputForWin7.zip)
