### ISSUE TITLE
地图加载不完整

### ISSUE THREAD

**Issue by wagayaluda** [mistzzt/TShock#5]
http://www.terrariaserver.cn/wp-content/uploads/2018/02/%E6%8D%95%E8%8E%B7.png
右边缺了一块emmm
已经确定不是网络延迟的问题，本地服务器也是这样。
但是用原版服务器端就没有出现这个问题

**Comment by mistzzt** [comment]
请参照[此issue](https://github.com/Pryaxis/TShock/issues/1378)。
原版是指游戏*TerrariaServer.exe*？
看上去这并不是与中文版有关的问题。
